### ISSUE TITLE
disconnect

### ISSUE THREAD

**Issue by 93Kamuran** [wakiyamap/electrum-mona#6]
I use Electrum-mona with my Trezor wallet. Firstly Electrum connects a server automatically. I use electrum RPC commands to watch my transactions with curl, I send RPC request periodically like "history" command. When some times pass Electrum disconnect from the server and does not reconnect again.
If I reconnect electrum to server manually It can connect and I see the green light again but curl commands doesn't get any response from electrum RPC.

**Comment by wakiyamap** [comment]
Thanks for issue.

First. Please tell me your version of electrum.
3.3.8?

Second. If possible, write the details of the error.
I'm not sure why I use curl when I use a GUI.

I'm sorry if it's a weird translation because I use google translation.

**Comment by 93Kamuran** [comment]
> Thanks for issue.
> 
> First. Please tell me your version of electrum.
> 3.3.8?
> 
> Second. If possible, write the details of the error.
> I'm not sure why I use curl when I use a GUI.
> 
> I'm sorry if it's a weird translation because I use google translation.

Thank you for response. I have website accepts  some crypto currencies. So I use electrums for get payments.  The electrums version is 3.3.8. I dont understand why my elecrums does not reconnect when disconnected or is there anyway you know connect them with rpc command?

**Comment by wakiyamap** [comment]
You used the GUI to check the connection, right?
I want to reproduction what is happening to you.
So please tell me what command line you entered.

```
$./run_electrum -D /tmp/alice stop
$./run_electrum -D /tmp/alice daemon -d
$./run_electrum -D /tmp/alice load_wallet
$./run_electrum -D /tmp/alice getbalance
```

**Comment by 93Kamuran** [comment]
My electrum wallets are running with .exe (GUI). When. I start Virtual
Machine a service starts electrums row by row. I can see All electrums on
the screen that are connected. My API  loads wallets with the curl command.
Then API gets history periodically. After a few hours (some times minutes)
electrums disconnect from server (maybe internet connection causing this
situation). I actually want to reconnect electrums automatically or with
RPC command. Because If I get any payment when the red light shining. I
cannot get a notification on my website

Jin Eguchi <notifications@github.com>, 9 Mar 2020 Pzt, 05:28 tarihinde şunu
yazdı:

**Comment by wakiyamap** [comment]
Ok. Please wait for a while so I will try to reproduce it.
If I can't reproduce it, I can't fix it.

**Comment by wakiyamap** [comment]
inactive.
Please reopen if there is a problem.
