### ISSUE TITLE
Electrum Zcore Wallet do not connected to the network

### ISSUE THREAD

**Issue by JakubM9** [wakiyamap/electrum-mona#8]
Hi, i make a request for a new transaction - collateral for a new MN - and send a coins 5000 ZCR but Ellectrum Zcore do not connected to the network and still have some errors... Could anybody helo me with this ? Thank you very much.

**Comment by wakiyamap** [comment]
This is a repository of electrum-mona.
Maybe……this one?
https://github.com/zcore-coin/electrum-wallet
